language:
- python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: EJj0UH7uW+0OL/+DdUafyRJQx8htgiRIBcTbccBWXq0rzHF/Oj2EeyXZEMlOCTPDYVz/2vfMMVzHoWoQDq938u1CE1KZMdghwvJf2VRb3d5JfmddzgCIemz+ay50xDPEFW54OYqKunQd1peJjqYX6+ZtRFGiAYyfDELJdO4AouxeLSnJCf1TYEx6MeBWNY0WNsXnGlR5v2ajapOO72ztu5DlZNFQEAF9rAH+jHwzHX8reFkYLxDpOiG45c73QwlZKTMkPY/Z05ksuzeQhTwbFI4O6jMZ8ONe0G8ZFmgg61M/ojQxDiGxcnxPrU5N15rCoSKibZKFDMS4o6u2l7rnsCuo/zVLIwHpE3wjAyBpCqhpt8ovOYDUaFZmvkSWohh5l+pl5iTxIuh/6mCIo80hLsiLoWw6X2MUSoUGIOD4xhmq6SDOfqqZY0DZCc64oTfu+lcWo4MmIRPZQvjQ9c6WcUb4604pxQWely1HQV4poC93H2uPGoBmu14SSAsMWOA40NSuX/uO/WcwMbec4+g/ESIDzAUTUHEkRyoj5gi4GRtkno0vnKjr8iXXs9UX3opVbEFEPBewO2MGpmbLUd5b22tuZm6tazmVC9CdVYoCjT8DSL249Udo/v5cDPPD4Trf9octXYx+dQBsel3GZIqNKKSP2UjWOelZD9fTANC6wdE=
  app: flasktaskr_project
  on:
    repo: Mwithiga/flasktaskr_project
